exports.databaseTables = {
  USERS: "users",
  PORTFOLIO: "portfolio",
  PORTFOLIOITEM: "portfolio_item",
  PORTFOLIOIDELIVERABLES: "portfolio_deliverables",
  PORTFOLIOCONTENT: "portfolio_content",
  HOMEPAGECONTENT: "homepage_content",
  WHATWEDO: "what_do_we_do",
  PARTNERS: "partners",
  COMMENT: "comment",
  AWARDS: "awards",
  TEAMS: "teams",
  JOBS: "jobs",
  COMMENTSTAFF: "comment_staff",
  BLOG: "blog",
  BLOGDETAILS: "blog_details",
  ABOUT: "about",
  ABOUTS_SLIDER: "about_slider",
  BANNER: "banners",
  CAREER_SLIDER: "career_slider",
  NEXT_POST: "next_post",
};
